disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - conditional_returns_on_newline
  - force_unwrapping
  - empty_count
  - missing_docs
  - operator_usage_whitespace

included:
  - SimpleDefaults

excluded:
  - Pods
